parameters:
    # Number of visit allowed before restricting the course page for an user. 
    course_access.visit_limit: 3
    # Number of day to give access to course page.
    course_access.day_limit: 1

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
