version: '3.9'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
    ports:
      - '3306:3306'
  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './apps/backend/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/backend/:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000