<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ5rB63x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ5rB63x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ5rB63x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ5rB63x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ5rB63x\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q5rB63x',
    'container.build_id' => 'df0d7588',
    'container.build_time' => 1662390294,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ5rB63x');
